### ISSUE TITLE
Cholmod error 'X and/or Y have wrong dimensions'

### ISSUE THREAD

**Issue by kauedesousa** [hturner/PlackettLuce#24] opened 2017-12-07 22:39 UTC
Happen when applying pltree in bagging using many attributes (> 62)

**Comment by kauedesousa** [comment] 2017-12-08 16:11
Amplify the minsize in pltree() avoid this problem.

**Comment by hturner** [comment] 2017-12-08 18:06
Glad this solved the problem for you, but I will keep this open to check if there is an issue with selecting zero or only one element of a grouped_rankings object (or if there is an issue with partykit that needs reporting).

**Comment by hturner** [comment] 2018-02-07 20:06
Selecting zero or one element of a grouped_rankings objects seems to work fine and I can't reproduce the error, so closing this now.

**Closed as completed** 2018-02-07 20:06 UTC
